In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib import rcParams
%matplotlib inline
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.model_selection import GridSearchCV

In [4]:
data = pd.read_csv('../../session_18/code/creditcard.csv')
data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [3]:
data = data.drop(['Time'], axis=1)
data.head()

,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,0.090794,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,-0.166974,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,0.207643,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,-0.054952,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,0.753074,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [4]:
x = data.drop(['Class'], axis=1)
y = data['Class']

In [5]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [14]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score , confusion_matrix, classification_report

In [10]:
hyper_param = {'criterion':['entropy'], 'max_depth':[4,6], 'n_estimators':[10, 20, 25], 'max_features':['sqrt']}

In [ ]:
tree_GS_param = GridSearchCV(RandomForestClassifier(),hyper_param, scoring='roc_auc', cv=5, n_jobs=-1)
tree_training = tree_GS_param.fit(x_train, y_train)
print('the best parameter is : ', tree_training.best_params_)
print('the best estimator is : ', tree_training.best_estimator_)
print('the best score is : ', tree_training.best_score_)

the best parameter is :  {'criterion': 'entropy', 'max_depth': 6, 'max_features': 'sqrt', 'n_estimators': 25}
the best estimator is :  RandomForestClassifier(criterion='entropy', max_depth=6, n_estimators=25)
the best scorw is :  0.9770857752592242

In [12]:
y_pred = tree_GS_param.predict(x_test)

In [15]:
cm1 = confusion_matrix(y_test, y_pred)

print(cm1)

print(classification_report(y_test, y_pred, target_names=["Safe", "Fraud"]))
 
#Calculate sensitivity and specificity
 
total1=sum(sum(cm1))

accuracy1=(cm1[0,0]+cm1[1,1])/total1

print ('Accuracy : ', accuracy1)
 
sensitivity1 = cm1[0,0]/(cm1[0,0]+cm1[0,1])

print('Sensitivity : ', sensitivity1 )
 
specificity1 = cm1[1,1]/(cm1[1,0]+cm1[1,1])

print('Specificity : ', specificity1)

[[56861     3]
 [   25    73]]
              precision    recall  f1-score   support

        Safe       1.00      1.00      1.00     56864
       Fraud       0.96      0.74      0.84        98

    accuracy                           1.00     56962
   macro avg       0.98      0.87      0.92     56962
weighted avg       1.00      1.00      1.00     56962

Accuracy :  0.9995084442259752
Sensitivity :  0.9999472425436128
Specificity :  0.7448979591836735

In [ ]:
from sklearn.ensemble import GradientBoostingClassifier, GradientBoostingRegressor

gbc_param = {
    'n_estimators':[100,200],
    'learning_rate':[.01, 0.1],
    'max_depth':[3, 4],
    'subsample':[0.8, 1.0],
    'min_samples_split':[2, 5]
}

tree_GSB_param = GridSearchCV(GradientBoostingClassifier(),gbc_param, scoring='roc_auc', cv=5, n_jobs=-1)
tree_training_bost = tree_GSB_param.fit(x_train, y_train)س
print('the best parameter is : ', tree_training_bost.best_params_)
print('the best estimator is : ', tree_training_bost.best_estimator_)
print('the best score is : ', tree_training_bost.best_score_)

the best parameter is :  {'learning_rate': 0.01, 'max_depth': 4, 'min_samples_split': 5, 'n_estimators': 200, 'subsample': 0.8}
the best estimator is :  GradientBoostingClassifier(learning_rate=0.01, max_depth=4, min_samples_split=5,
                           n_estimators=200, subsample=0.8)
the best score is :  0.9597017945384746

In [20]:
import pickle

with open("tree_training_boost.pkl", "wb") as file:
    pickle.dump(tree_training_bost, file)

In [7]:
from xgboost import XGBClassifier